# Numpy Paketi: 

Mert Kaan Cukadar: mertkaacukadar@ieee.com

Listeler yapısal olarak kendi aralarında matematiksel işlem yapmak için uygun değillerdir. Matlabdan ya da octave dan alışık olunan gibi matris gib davranmaz listeler. Bunun için modüllere ihtiyaç duyarız. <b>Numpy</b> modülü listerde matematiksel işlmeler yapılabilmesi için geliştirilmiş bir pakettir. 


## Numpy arrays (Numpy dizileri):
her biri aynı veri yapısında bulunacak şekilde diziler hazırlanır. Örnek vermek gerikrse sayı verileri eğer strig bir veri bulunan listenin içerisinde ise strig veri tipi olarak çevirilir.

In [3]:
import numpy as np
variables = np.array(["Rover", 5 , 8])
print(type(variables[1]))


<class 'numpy.str_'>


Gördüğünüz üzere array metodunu kullanarak aynı veri tipine sahip liste oluşturduk. Şimdi listerler arasında matematiksel işlem yapma ortamını oluşturabiliriz. Array metodunu kullanalım...

In [9]:
veri_1 = [1 , 2 , 3 ,4 ,5,]
veri_2 = [4 , 2, 5, 4 ,5]
veri_np = np.array(veri_1)
veri_np1 = np.array(veri_2)

ortalama = (veri_np + veri_np1) / 2
print(ortalama)


[2.5 2.  4.  4.  5. ]


In [7]:
# ya da bu iki listeyi birbirleriyle çarpabiliriz
veri_np1*veri_np

array([ 4,  4, 15, 16, 25])

Konu hakkında dikkat edilmesi gereken şey <b> bu veri gruplarının uzulukları işlem yapabilmeniz için aynı olmalıdır... <b/>

In [11]:
veri_np < 4

array([ True,  True,  True, False, False])

In [12]:
veri_np[veri_np < 4]

array([1, 2, 3])

koşulu sağlayan verileri çekmenin bir yolu yukarıda gösterilmiştir. Şimdi sayı dizileri oluşturmak için kullanılan metolara bakalım. 

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

kullandıımız <b> arange ve linspace </b> metodları sıralı dizi oluşturmamızı sağlar arange analşılır ancak linspace şu şekilde çalışmaktadır. iki sayı arasında dizi elde etmek istiyorsanız bu dileri kaçtane olacağını söyleyerek çağırırsınız.

In [18]:
np.logspace(0 , 5) # verilerin logaritmasını alarak çıktı verir

array([1.00000000e+00, 1.26485522e+00, 1.59985872e+00, 2.02358965e+00,
       2.55954792e+00, 3.23745754e+00, 4.09491506e+00, 5.17947468e+00,
       6.55128557e+00, 8.28642773e+00, 1.04811313e+01, 1.32571137e+01,
       1.67683294e+01, 2.12095089e+01, 2.68269580e+01, 3.39322177e+01,
       4.29193426e+01, 5.42867544e+01, 6.86648845e+01, 8.68511374e+01,
       1.09854114e+02, 1.38949549e+02, 1.75751062e+02, 2.22299648e+02,
       2.81176870e+02, 3.55648031e+02, 4.49843267e+02, 5.68986603e+02,
       7.19685673e+02, 9.10298178e+02, 1.15139540e+03, 1.45634848e+03,
       1.84206997e+03, 2.32995181e+03, 2.94705170e+03, 3.72759372e+03,
       4.71486636e+03, 5.96362332e+03, 7.54312006e+03, 9.54095476e+03,
       1.20679264e+04, 1.52641797e+04, 1.93069773e+04, 2.44205309e+04,
       3.08884360e+04, 3.90693994e+04, 4.94171336e+04, 6.25055193e+04,
       7.90604321e+04, 1.00000000e+05])

## Boyutlu veri nesneleri

In [21]:
dizi = np.array([[1, 2 , 3 ,4],[1,2,3,4],[1, 11,1,1]])
print(dizi)

[[ 1  2  3  4]
 [ 1  2  3  4]
 [ 1 11  1  1]]


eğer daha önce matrislerle programa yaptısanız matrislerden veriler çağırıırken enine ve boyuna olmak üzere ayrı ayrı belirtilir. Örneklendirmek gerekirse...

In [24]:
dizi[0:2,0:2]# ilk iki satırı ve ilk iki stunun verilerini çekelim...

array([[1, 2],
       [1, 2]])

Veri grubunun boyutlarını öğrenmek için <b> .shape </b> metodu kullanılır. 

In [26]:
dizi.shape

(3, 4)

In [27]:
# şimdi 3 boyulu bir dizi üretelim
dizi_3 = np.array([[[1,1,1,1],
                    [1,1,1,1],[1,1,1,1]],
                   [[2,2,2,2],[2,2,2,2],[2,2,2,2]]])

In [28]:
dizi_3 # 3 boyutlu bir dizi tanımladık...


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [29]:
dizi_3.shape

(2, 3, 4)

yukarıda .shape metodunu çağırdığımızda tüksekliği iki olan 3 e 4 lük birer dizi oluşturduğumuzu okumuş oluyoruz. Ek olarak şunu söyleyebilirim elimizdeki bir dizinin transpose unu almak için <b> .T </b> metodu kullanılır. Şu şekilde ifade edilebilir.

In [30]:
dizi.T

array([[ 1,  1,  1],
       [ 2,  2, 11],
       [ 3,  3,  1],
       [ 4,  4,  1]])

In [31]:
dizi

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 1, 11,  1,  1]])

Aralarındaki döüşümü dikkatli bakarsanız görebilirsiniz. :)

## Örnekler:
Şimdi dilerseniz bir kaç örnek ile bu paketteki metodları hep birlikte kullanalım. ilk olarak matris çarpımlarını normal çarpımlarını inceleyelim... örneklendirmek için ikişer tane Numpy dizisi ele alalım;


In [37]:
a_array = np.array([1,2,2])
b_array = np.array([3,4,5])

print(a_array * b_array)

[ 3  8 10]


Örnekte göreceğiniz üzere burada iki vektörün product rule' a göre çarpımını görebilirsiniz.
$$ a_a \times b_a \times \cos\theta $$

eğer bu iki diziyi birer matris olarak çarpmak isterseniz <b>np.matmul</b> operatörünü kullanınız. hepbirlikte deneyelim küçük bir hata yaparakta ek bir şey daha öğrenelim. 

In [38]:
np.matmul(a_array , b_array) #hatalı

21

In [39]:
bt_array = b_array.T

In [43]:
np.matmul(a_array,bt_array) # doğru 

21

Burada yapılan hata aslında aslında matematiksel bir hatadır 1 e 2 lik bir matris ile 1 e 2 lik bir matrisi normal koşullarda çarpamazsınız kullandığınız metod bunun önüne geçiyor ancak ikinci matrisi transpose ederseniz ve değerleri bu şekilde çarparsanız yani (1 e 2 lik bir matris ile 2 ye 1 lik bir matrisi çarparsanız) matematiksel olarakta doğru bir işlem gerçekleştirş olursunuz. 

In [44]:
dizi 

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 1, 11,  1,  1]])

Şimdi ise boyutlu listelerin içerisinde son olarak bi toplam fonksiyonu kullanalım. 


In [45]:
np.sum(dizi[:,2])

7

In [46]:
dizi[:,2]

array([3, 3, 1])